<a href="https://colab.research.google.com/github/Mmotaharinia/Numpy_Data_Engineering_Skills/blob/main/C_Numpy_Data_Engineering_Skills.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Some useful Liobraries
from numpy.lib.function_base import kaiser
from numpy.core.function_base import linspace
import pandas as pd
import numpy as np
import math  
import timeit
%precision 2
# Measure the time of code being run
tim_comp=timeit.timeit(number=1000)
print('tim_comp=',tim_comp)

tim_comp= 2.3887999986982322e-05


In [ ]:
#query a simple list
lst=[[1,2,3,6],[0,0,0,0],[9,9,9,9]]
print(lst[2][0])
#add an item
lst.append([777,777,777,777])
print(lst)
#remove an item
lst.pop(3)
print(lst)
len(lst)

9
[[1, 2, 3, 6], [0, 0, 0, 0], [9, 9, 9, 9], [777, 777, 777, 777]]
[[1, 2, 3, 6], [0, 0, 0, 0], [9, 9, 9, 9]]


3

In [ ]:
#query a dictionary # each dictionary has a key that correspond to one or a list of items
edic={'Alison':[19,20],
   'Jack':[18,9],
   'Mo':[20,7]}
print('edic=',edic)
#add an item
edic['Lena']=17
print('edic=',edic)
#remove an item
edic.pop('Lena')
print('edic=',edic)
print('edic["Mo"][1]',edic['Mo'][1])
edic['Alison'].append(19.5) # cause that is basically a list of items
print('edic=',edic)
len(edic)

edic= {'Alison': [19, 20], 'Jack': [18, 9], 'Mo': [20, 7]}
edic= {'Alison': [19, 20], 'Jack': [18, 9], 'Mo': [20, 7], 'Lena': 17}
edic= {'Alison': [19, 20], 'Jack': [18, 9], 'Mo': [20, 7]}
edic["Mo"][1] 7
edic= {'Alison': [19, 20, 19.5], 'Jack': [18, 9], 'Mo': [20, 7]}


3

In [ ]:
#concat two dics
edic2={'MK':[19,20],
   'JK':[18,9],
   'MK':[20,7]}
edic2.update(edic)
edic2

{'Alison': [19, 20, 19.50],
 'JK': [18, 9],
 'Jack': [18, 9],
 'MK': [20, 7],
 'Mo': [20, 7]}

In [ ]:
# Numerical Arrays/Matrices (Numpy)
#define an array and query a column vs row
exp_arr=np.array([[1,2,3],[3,3,3],[55,55,78],[4,4,4]])
#insert an additional row
exp_arr[:,0]=0
exp_arr[:,0]=[9,9,9,9]
print('exp_arr=',exp_arr,'\n')
print('first row=',exp_arr[0,:])
print('first column=',exp_arr[:,0])
# find the number of rows and columns
print('number of rows=',len(exp_arr[:,0]))
print('number of columns=',len(exp_arr[0,:]))

exp_arr= [[ 9  2  3]
 [ 9  3  3]
 [ 9 55 78]
 [ 9  4  4]] 

first row= [9 2 3]
first column= [9 9 9 9]
number of rows= 4
number of columns= 3


In [ ]:
#Matix slicing
b1=np.array([[1,2,3,4],[0,0,0,0],[99,99,99,99]])
b11=b1[1:3,0:2]
b111=np.delete(b1,1,axis=0)
print('b1=','\n',b1,'\n')
print('b11=','\n', b11,'\n')
print('b111=',b111,'\n')

b1= 
 [[ 1  2  3  4]
 [ 0  0  0  0]
 [99 99 99 99]] 

b11= 
 [[ 0  0]
 [99 99]] 

b111= [[ 1  2  3  4]
 [99 99 99 99]] 



In [ ]:
# array dimension
a=np.array([[1,2,3],[0,0,0],[55,55,78],[0,0,0]])
b=a.ndim
print("b=",b)

# find the dimensions of a matrix
c=a.shape
print('c=',c)

b= 2
c= (4, 3)


In [ ]:
#make a copy of a matrix, dataframe, list etc
exm_array=np.array([[1,2,3,'h'],['k','k','k','k']])
exm_array_copy=exm_array.copy()
print(exm_array_copy)

[['1' '2' '3' 'h']
 ['k' 'k' 'k' 'k']]


In [ ]:
# produce an array of random numbers
rand=np.random.rand(2,3) #dimension of the array 
rand_int=np.random.randint(1,1000,1000)
print('rand=',rand,'\n')
# produce a sequence between two numbers
seq=np.arange(10,50,4)
print('seq=',seq)
# divide an interval into x small intervals
lin_sp= np.linspace(0,1,5)
print('lin_sp=',lin_sp)

rand= [[0.95 0.47 0.1 ]
 [0.01 0.55 0.21]] 

seq= [10 14 18 22 26 30 34 38 42 46]
lin_sp= [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# produce a matrix of zeros or ones or full, or eye 
print('full=','\n',np.full([3,3],256),'\n')
print('Zeros=','\n',np.zeros((2,3)),'\n')
print('ones=','\n',np.ones((3,4)),'\n')
print('eye='+'\n',np.eye(3),'\n')



full= 
 [[256 256 256]
 [256 256 256]
 [256 256 256]] 

Zeros= 
 [[0. 0. 0.]
 [0. 0. 0.]] 

ones= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

eye=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [ ]:
# Array element wise operations
j=np.array([[1,2,3],[1,2,3]])
k=np.array([[10,20,30],[10,20,30]])
print('add=','\n',j+k)
print('div=','\n',j/k)

add= 
 [[11 22 33]
 [11 22 33]]
div= 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [ ]:
# Matrix multiplication
print('Matrix multiplication=','\n', (np.array([1,2,3])) @ (np.array([[1],[2],[3]])) )

Matrix multiplication= 
 [14]


In [ ]:
# sum, Mean, max, min, std, sqrt, of all the elements in a matrix
s=np.array([[1,2],[10,10]]) 
print('sum=',s.sum())
print('mean=',s.mean())
print('min=',s.min())
print('max=',s.max())
print('std=',s.std())
print('var=',s.var())

sum= 23
mean= 5.75
min= 1
max= 10
std= 4.264680527307995
var= 18.1875


In [ ]:
# Boolian condition on a matrix
n=np.array([0,1,2,10])
o=(n>5)
print('o=',o)

o= [False False False  True]


In [ ]:
# shape & reshape a matrix 
z=np.arange(1,16,1)
print('z=',z,'\n')
print('reshaped=','\n',z.reshape(3,5),'\n')
print('the_current_shape_is_:',z.shape)

z= [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

reshaped= 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

the_current_shape_is_: (15,)


In [ ]:
#matrix transpose
m_trans=np.array([[1,2,3,4,5,6],[0,0,0,0,0,0]])
print('m_trans=','\n',m_trans,'\n')
print('m_trans.T=','\n',m_trans.T)

m_trans= 
 [[1 2 3 4 5 6]
 [0 0 0 0 0 0]] 

m_trans.T= 
 [[1 0]
 [2 0]
 [3 0]
 [4 0]
 [5 0]
 [6 0]]


In [ ]:
#matrix concatenate
d1=np.array([[0,0,0],[1,1,1],[2,2,2]])
d11=np.array([[-1,-1,-1],[-9,-9,-9],[-88,-88,-88]])
print('d1=','\n',d1,'\n')
print('d11=','\n',d11,'\n')
d111=np.concatenate((d1,d11),axis=1)
print('d111=','\n',d111)

d1= 
 [[0 0 0]
 [1 1 1]
 [2 2 2]] 

d11= 
 [[ -1  -1  -1]
 [ -9  -9  -9]
 [-88 -88 -88]] 

d111= 
 [[  0   0   0  -1  -1  -1]
 [  1   1   1  -9  -9  -9]
 [  2   2   2 -88 -88 -88]]


In [ ]:
#Matrix elements
eye1=np.eye(4)
for j in range(len(eye1)):
  for i in range(len(eye1[0])):
    if eye1[j,i]>0:
      eye1[j,i]=1000
    elif eye1[j,i]==0:
      eye1[j,i]=2
    i=i+1
  j=j+1

print('eye1=','\n',eye1)

eye1= 
 [[1000.    2.    2.    2.]
 [   2. 1000.    2.    2.]
 [   2.    2. 1000.    2.]
 [   2.    2.    2. 1000.]]


In [ ]:
# using a csv file
#here we cannot read anything that is not a number(nan)
c1=np.genfromtxt("SPY_3.csv",delimiter=',',skip_header=0)
c1=np.delete(c1,0,axis=0)
c1=np.delete(c1,0,axis=1)
pd.DataFrame(c1).head(3)

0           1           2           3           4            5
0  371.779999  374.660004  371.230011  373.880005  368.959473   78520700.0
1  375.309998  375.450012  364.820007  368.790009  363.936462  110210800.0
2  368.100006  372.500000  368.049988  371.329987  366.442993   66426200.0